version: "3.9"

services:
  nginx-tls:
    build: ./docker/nginx-oqs
    container_name: tls-perf-nginx
    ports:
      - "4431:4431" # AES-GCM
      - "4432:4432" # ChaCha20-Poly1305
      - "8443:8443" # X25519+ML-KEM-768 hybrid
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./docker/nginx-oqs/conf.d:/etc/nginx/conf.d:ro
    environment:
      - TZ=Europe/Warsaw
